In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
print(a)
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)

type(a):  <class 'numpy.ndarray'>
a.dtype:  int32


In [4]:
'''
type是Python內建的函式，回傳數據結構(陣列)的類型
而dtype是Numpy的陣列屬性，會回傳陣列中的資料型態
'''

'\ntype是Python內建的函式，回傳數據結構(陣列)的類型\n而dtype是Numpy的陣列屬性，會回傳陣列中的資料型態\n'

In [33]:
# 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。
def is_dtype(a, t):
        return a.dtype is t
    
print(type('int'))
print(type(np.int))
print(np.dtype('int'))

<class 'str'>
<class 'type'>
int32


In [34]:
a = np.random.randint(10, size=6) 
print(a)
# 測試一
print(is_dtype(a, 'int')) # False

# 測試二
print(is_dtype(a, np.int)) # False

# 測試三
print(is_dtype(a, np.dtype('int'))) # True


[5 6 3 8 8 8]
False
False
True


In [26]:
# 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？
'''
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
'''

'''
# 從2的結果可知，is_dtype要求判斷輸入的t是否為np.dtype物件，所以用is作為比較較為精準
'''

'\ndef is_dtype(a, t):\n    return a.dtype is t\n\ndef is_dtype(a, t):\n    return type(a) == np.dtype(t)\n\ndef is_dtype(a, t):\n    return type(a) is np.dtype(t)\n'