In [1]:
import numpy as np

In [2]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [3]:
dt = np.dtype({'names':('name', 'sex', 'weight', 'rank', 'myopia'), 'formats':('U8','U8', float, int, bool)})
c = np.zeros(8,dtype = dt)
c

array([('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False)],
      dtype=[('name', '<U8'), ('sex', '<U8'), ('weight', '<f8'), ('rank', '<i4'), ('myopia', '?')])

In [10]:
c['name'] = name_list
c['sex'] = sex_list
c['weight'] = weight_list
c['rank'] = rank_list
c['myopia'] = myopia_list
c

array([('小明', 'boy', 67.5, 8,  True), ('小華', 'boy', 75.3, 1,  True),
       ('小菁', 'girl', 50.1, 5, False), ('小美', 'girl', 45.5, 4, False),
       ('小張', 'boy', 80.8, 7,  True), ('John', 'boy', 90.4, 6,  True),
       ('Mark', 'boy', 78.4, 2, False), ('Tom', 'boy', 70.7, 3, False)],
      dtype=[('name', '<U8'), ('sex', '<U8'), ('weight', '<f8'), ('rank', '<i4'), ('myopia', '?')])

In [25]:
boy_weight = c[c['sex'] == 'boy']['weight']
boy_weight_mean = np.mean(boy_weight)
girl_wight = c[c['sex'] == 'girl']['weight']
girl_weight_mean = np.mean(girl_wight)
print("全體體重平均: ",np.mean(c['weight']))
print("男生體重平均: ",boy_weight_mean)
print("女生體重平均: ", girl_weight_mean)

全體體重平均:  69.8375
男生體重平均:  77.18333333333332
女生體重平均:  47.8


In [6]:
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
'''
zeros建立的是由0組成的陣列
empty建立的是由極小的數組成的陣列(非常接近0)

empty的執行速度較zeros快一點，通常用於初始化一指定尺寸的陣列，對裡面的初始化資料並沒有要求。
// 參考

'''

'\nzeros建立的是由0組成的陣列\nempty建立的是由極小的數組成的陣列(非常接近0)\n\nempty的執行速度較zeros快一點，通常用於初始化一指定尺寸的陣列，對裡面的初始化資料並沒有要求。\n// 參考\n\n'

In [8]:
# 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [32]:
# 轉換前
a = np.random.rand(2, 3)
a

array([[0.91137154, 0.05864729, 0.24119086],
       [0.62925367, 0.69984238, 0.04498534]])

In [35]:
# 轉換後
a = np.array(a, dtype = int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
# 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。
m = 20
n = 40
a = 20 + (40-20) * np.random.rand(2, 3)
a

array([[30.34089597, 39.70446657, 24.11525567],
       [31.56778878, 27.46793859, 38.45259625]])