In [1]:
import numpy as np

In [2]:
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

In [3]:
# 1. [簡答題] 請問下列程式碼，運算結果分別為何？
print(a + a)
print(a + b)
print(a + c)
print(a + d)
# print(a + e)  # 不符合Boardcast原則

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


In [7]:
# 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？
A = np.ones(3)*1
B = np.ones(3)*2

print(A)
print(B)

# 不用迴圈
print((A + B)*(-A/2))

# 用迴圈
ANS = []
for i in np.arange(A.size):
    #j = B[i]
    ANS.append((A[i] + B[i])* (-A[i]/2))
        
#print(index_array_B)
print(ANS)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]
[-1.5, -1.5, -1.5]


In [5]:
A = np.ones((1,6))
B = np.ones((6,1))
print(A * B) # 外積
print(np.dot(A, B)) # 內積
print(np.outer(A, B))# 外積
print(A @ B) # 內積

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
