In [16]:
import numpy as np

In [18]:
# 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
a = np.arange(1,12) #產生一個 1-11 的一維陣列

for i in a-1:
    if (a[i] > 2) & (a[i] < 7):
        a[i] = -a[i]
        
print(a)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [24]:
# 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？

A = np.random.rand(3, 6)
print(A) # print A
print(A[A > 0.5]) # 判斷大於0.5的數
print(np.size(A[A > 0.5])) # 判斷大於0.5的數有幾個



[[0.96186715 0.9149768  0.17417411 0.40246162 0.91509886 0.43780963]
 [0.84728866 0.59435752 0.93226045 0.3387695  0.72168937 0.02085105]
 [0.38201746 0.0093327  0.39273979 0.29291664 0.91674808 0.84401008]]
[0.96186715 0.9149768  0.91509886 0.84728866 0.59435752 0.93226045
 0.72168937 0.91674808 0.84401008]
9
