In [1]:
import numpy as np

#1. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open("old_array.npz", 'wb') as f:
    np.savez(f, array1, array2)
    

In [9]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
array3 = np.array([[4,5,6],[1,2,3]])

old_array = np.load("old_array.npz")

with open("New_array.npz", 'wb') as f:
    np.savez(f, old_array['arr_0'], old_array['arr_1'], array3)
    
# 驗證答案
temp_array = np.load("New_array.npz")
temp_array.files
print(temp_array['arr_0'])
print(temp_array['arr_1'])
print(temp_array['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
